APRIL_WINDOW_TITLE_ENG = "April Music Player - Digest Lyrics"
APRIL_WINDOW_TITLE_BUR = "April Music Player - သီချင်းစာသားများကို အလွတ်ကျက်ပစ်လိုက်စမ်း" # lol better come up with something

APRIL_WINDOW_TITLE = {
    'ENG': APRIL_WINDOW_TITLE_ENG,
    'BUR': APRIL_WINDOW_TITLE_BUR,
}

FILTER_SONGS_FROM_PLAYLIST_ENG = "Filter Songs From the Playlist..."
FILTER_SONGS_FROM_PLAYLIST_BUR = ""

FILTER_SONGS_FROM_PLAYLIST = {
    'ENG': FILTER_SONGS_FROM_PLAYLIST_ENG,
    'BUR': FILTER_SONGS_FROM_PLAYLIST_BUR
}

SEARCH_SONG_BY_NAME_ENG = "Search Song by Name"
SEARCH_SONG_BY_NAME_BUR = ""

SEARCH_SONG_BY_NAME = {
    'ENG': SEARCH_SONG_BY_NAME_ENG,
    'BUR': SEARCH_SONG_BY_NAME_BUR
}

FILTER_SONGS_FROM_PLAYLIST_TOOLTIP_ENG = "Shortcut: [Ctrl + Shift + F]"
FILTER_SONGS_FROM_PLAYLIST_TOOLTIP_BUR = ""

FILTER_SONGS_FROM_PLAYLIST_TOOLTIP= {
    'ENG': FILTER_SONGS_FROM_PLAYLIST_TOOLTIP_ENG,
    'BUR': FILTER_SONGS_FROM_PLAYLIST_TOOLTIP_BUR
}

LYRICS_NOT_FOUND_TITLE_ENG = "No Lyrics Found"
LYRICS_NOT_FOUND_TITLE_BUR = "စာသားမရှိပါ"

LYRICS_NOT_FOUND_TITLE = {
    'ENG': LYRICS_NOT_FOUND_TITLE_ENG,
    'BUR': LYRICS_NOT_FOUND_TITLE_BUR,
}

LYRICS_NOT_FOUND_ENG = "There is no lyrics file associated with this song."
LYRICS_NOT_FOUND_BUR = """ဆက်စပ်သောသီချင်းစာသား file မရှိပါ။ သီချင်းပေါ်မှာ right click နှိပ်၍ download with lrc downloader ဖြင့် download လုပ်ကြည့်ပါ။ lrcdb တွင်စာသားရှိလျှင်ရနိုင်ပါသည်"""

LYRICS_NOT_FOUND = {
    'ENG': LYRICS_NOT_FOUND_ENG,
    'BUR': LYRICS_NOT_FOUND_BUR,
}

DOWNLOAD_WITH_LRC_ENG = "Download Lyrics with lrcdl"
DOWNLOAD_WITH_LRC_BUR = "lrcdl သုံး၍ စာသားဒေါင်းလုပ် လုပ်ကြည့်ပါမည်။"

DOWNLOAD_WITH_LRC = {
    'ENG': DOWNLOAD_WITH_LRC_ENG,
    'BUR': DOWNLOAD_WITH_LRC_BUR
}

COPY_SONG_PATH_ENG = "Copy Song Path (Ctrl+C)"
COPY_SONG_PATH_BUR = ""

COPY_SONG_PATH = {
    'ENG': COPY_SONG_PATH_ENG,
    'BUR': COPY_SONG_PATH_BUR
}

EDIT_META_DATA_ENG = "Edit Song's Metadata"
EDIT_META_DATA_BUR = ""

EDIT_META_DATA = {
    'ENG': EDIT_META_DATA_ENG,
    'BUR': EDIT_META_DATA_BUR
}

SELECT_AN_IMAGE_FOR_BACKGROUND_TITLE_ENG = "Select an Image file for lrc display background image"
SELECT_AN_IMAGE_FOR_BACKGROUND_TITLE_BUR = ""

SELECT_AN_IMAGE_FOR_BACKGROUND_TITLE = {
    'ENG': SELECT_AN_IMAGE_FOR_BACKGROUND_TITLE_ENG,
    'BUR': SELECT_AN_IMAGE_FOR_BACKGROUND_TITLE_BUR
}

LOAD_BACKGROUND_IMAGE_TITLE_ENG = "Load Background Image"
LOAD_BACKGROUND_IMAGE_TITLE_BUR = ""

LOAD_BACKGROUND_IMAGE_TITLE = {
    'ENG': LOAD_BACKGROUND_IMAGE_TITLE_ENG,
    'BUR': LOAD_BACKGROUND_IMAGE_TITLE_BUR
}

NO_FILE_SELECTED_TITLE_ENG = "No File Selected"
NO_FILE_SELECTED_TITLE_BUR = ""

NO_FILE_SELECTED_TITLE = {
    'ENG': NO_FILE_SELECTED_TITLE_ENG,
    'BUR': NO_FILE_SELECTED_TITLE_BUR
}

DID_NOT_SELECT_IMAGE_FILE_ENG = "You did not select any file"
DID_NOT_SELECT_IMAGE_FILE_BUR = ""

DID_NOT_SELECT_IMAGE_FILE = {
    'ENG': DID_NOT_SELECT_IMAGE_FILE_ENG,
    'BUR': DID_NOT_SELECT_IMAGE_FILE_BUR
}